### PR TITLE
Allow developer to run `spark upgrade .` to upgrade spark installation.

### PR DESCRIPTION
**Pull request by crynobone**
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

### CODE REVIEW

**Comment by taylorotwell** [comment]
I thought Spark already included an update command? @themsaid

**Comment by themsaid** [comment]
Yes `php artisan spark:update` updates the project to the latest minor version, a `--major` flag can be used to upgrade it to the latest major release.

**Comment by taylorotwell** [comment]
@crynobone maybe you can explain but we already have an update command?

**Comment by crynobone** [comment]
I just started a project few days ago and the first thing I notice there wasn't a documentation on getting the update when installing with spark installer. Didn't expect it to be available with spark itself.

**Pull request closed without merging**
